{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraform-generator.fullname" . }}-backend-secret
  namespace: {{ include "terraform-generator.namespace" . }}
  labels:
    {{- include "terraform-generator.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.backend.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
