from __future__ import annotations

import io
import zipfile
from datetime import datetime, timezone

from app.models.schemas import GeneratedFile


def _generate_readme(files: list[GeneratedFile], provider: str, summary: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    file_listing = "\n".join(
        f"- **`{f.filename}`** -- {f.description}" for f in files
    )

    return f"""\
# Generated Terraform Configuration

> Auto-generated by **AI-Powered Terraform Code Generator** on {now}

## Provider

`{provider}`

## Summary

{summary}

## Files

{file_listing}

## Getting Started

```bash
# 1. Review and edit terraform.tfvars.example, then rename it:
cp terraform.tfvars.example terraform.tfvars

# 2. Initialise Terraform:
terraform init

# 3. Preview the changes:
terraform plan

# 4. Apply:
terraform apply
```

## Security Notes

- Review all IAM policies and security groups before applying.
- Never commit `terraform.tfvars` with real secrets to version control.
- Store the Terraform state in a remote backend (S3, GCS, Azure Blob)
  with encryption and locking enabled.
"""


def create_zip(
    files: list[GeneratedFile],
    provider: str = "aws",
    summary: str = "",
) -> bytes:
    """Create an in-memory zip archive containing all generated files
    plus an explanatory README."""

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add the generated Terraform files
        for f in files:
            zf.writestr(f.filename, f.content)

        # Add README
        readme = _generate_readme(files, provider, summary)
        zf.writestr("README.md", readme)

    return buf.getvalue()
