import { useState, useCallback } from 'react';
import { Code2, History, Zap } from 'lucide-react';
import DescriptionInput from '@/components/DescriptionInput';
import CodeViewer from '@/components/CodeViewer';
import SecurityNotes from '@/components/SecurityNotes';
import HistoryPanel from '@/components/HistoryPanel';
import { api } from '@/lib/api';
import type {
  CloudProvider,
  SecurityLevel,
  GeneratedFile,
  ValidationResult,
} from '@/types';

// Demo/mock data for when the backend is not connected
const MOCK_FILES: Record<CloudProvider, GeneratedFile[]> = {
  aws: [
    {
      filename: 'main.tf',
      content: `# --------------------------------------------------
# AWS Infrastructure - Generated by Terraform Generator
# --------------------------------------------------

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket         = "my-terraform-state"
    key            = "infrastructure/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}

# ----- VPC -----
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "\${var.project_name}-vpc"
  cidr = var.vpc_cidr

  azs             = var.availability_zones
  private_subnets = var.private_subnet_cidrs
  public_subnets  = var.public_subnet_cidrs

  enable_nat_gateway   = true
  single_nat_gateway   = var.environment != "production"
  enable_dns_hostnames = true
  enable_dns_support   = true

  enable_flow_log                      = true
  create_flow_log_cloudwatch_log_group = true
  create_flow_log_iam_role             = true

  tags = {
    Component = "networking"
  }
}

# ----- Security Groups -----
resource "aws_security_group" "bastion" {
  name_prefix = "\${var.project_name}-bastion-"
  vpc_id      = module.vpc.vpc_id
  description = "Security group for bastion host"

  ingress {
    description = "SSH from allowed CIDRs"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = var.allowed_ssh_cidrs
  }

  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = true
  }
}

# ----- Bastion Host -----
resource "aws_instance" "bastion" {
  ami                    = data.aws_ami.amazon_linux.id
  instance_type          = "t3.micro"
  subnet_id              = module.vpc.public_subnets[0]
  vpc_security_group_ids = [aws_security_group.bastion.id]
  key_name               = var.key_pair_name

  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }

  root_block_device {
    encrypted   = true
    volume_type = "gp3"
  }

  tags = {
    Name      = "\${var.project_name}-bastion"
    Component = "bastion"
  }
}

data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}
`,
      description: 'Main infrastructure configuration',
      language: 'hcl',
    },
    {
      filename: 'variables.tf',
      content: `# --------------------------------------------------
# Input Variables
# --------------------------------------------------

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Name of the project"
  type        = string
  default     = "my-infra"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "development"

  validation {
    condition     = contains(["development", "staging", "production"], var.environment)
    error_message = "Environment must be development, staging, or production."
  }
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "availability_zones" {
  description = "List of availability zones"
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b", "us-east-1c"]
}

variable "private_subnet_cidrs" {
  description = "CIDR blocks for private subnets"
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for public subnets"
  type        = list(string)
  default     = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
}

variable "allowed_ssh_cidrs" {
  description = "CIDR blocks allowed for SSH access"
  type        = list(string)
  default     = []
}

variable "key_pair_name" {
  description = "EC2 key pair name for bastion host"
  type        = string
  default     = ""
}
`,
      description: 'Input variable definitions',
      language: 'hcl',
    },
    {
      filename: 'outputs.tf',
      content: `# --------------------------------------------------
# Outputs
# --------------------------------------------------

output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "private_subnet_ids" {
  description = "IDs of the private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnet_ids" {
  description = "IDs of the public subnets"
  value       = module.vpc.public_subnets
}

output "nat_gateway_ips" {
  description = "Elastic IPs of the NAT gateways"
  value       = module.vpc.nat_public_ips
}

output "bastion_public_ip" {
  description = "Public IP of the bastion host"
  value       = aws_instance.bastion.public_ip
}

output "bastion_security_group_id" {
  description = "Security group ID of the bastion host"
  value       = aws_security_group.bastion.id
}
`,
      description: 'Output values',
      language: 'hcl',
    },
    {
      filename: 'terraform.tfvars',
      content: `# --------------------------------------------------
# Variable Values
# --------------------------------------------------

aws_region   = "us-east-1"
project_name = "my-infra"
environment  = "development"

vpc_cidr           = "10.0.0.0/16"
availability_zones = ["us-east-1a", "us-east-1b", "us-east-1c"]

private_subnet_cidrs = [
  "10.0.1.0/24",
  "10.0.2.0/24",
  "10.0.3.0/24",
]

public_subnet_cidrs = [
  "10.0.101.0/24",
  "10.0.102.0/24",
  "10.0.103.0/24",
]

allowed_ssh_cidrs = ["0.0.0.0/0"]  # Restrict this in production!
key_pair_name     = "my-keypair"
`,
      description: 'Variable values for this environment',
      language: 'hcl',
    },
  ],
  gcp: [
    {
      filename: 'main.tf',
      content: `# --------------------------------------------------
# GCP Infrastructure - Generated by Terraform Generator
# --------------------------------------------------

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# ----- VPC Network -----
resource "google_compute_network" "main" {
  name                    = "\${var.project_name}-vpc"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "private" {
  name          = "\${var.project_name}-private"
  ip_cidr_range = var.private_subnet_cidr
  region        = var.region
  network       = google_compute_network.main.id

  private_ip_google_access = true

  log_config {
    aggregation_interval = "INTERVAL_5_SEC"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}

# ----- Cloud NAT -----
resource "google_compute_router" "main" {
  name    = "\${var.project_name}-router"
  region  = var.region
  network = google_compute_network.main.id
}

resource "google_compute_router_nat" "main" {
  name                               = "\${var.project_name}-nat"
  router                             = google_compute_router.main.name
  region                             = var.region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"

  log_config {
    enable = true
    filter = "ERRORS_ONLY"
  }
}
`,
      description: 'Main GCP infrastructure',
      language: 'hcl',
    },
    {
      filename: 'variables.tf',
      content: `variable "project_id" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region"
  type        = string
  default     = "europe-west1"
}

variable "project_name" {
  description = "Project name prefix"
  type        = string
  default     = "my-infra"
}

variable "private_subnet_cidr" {
  description = "CIDR for private subnet"
  type        = string
  default     = "10.0.1.0/24"
}
`,
      description: 'Variable definitions',
      language: 'hcl',
    },
    {
      filename: 'outputs.tf',
      content: `output "network_id" {
  description = "VPC network ID"
  value       = google_compute_network.main.id
}

output "subnet_id" {
  description = "Private subnet ID"
  value       = google_compute_subnetwork.private.id
}

output "router_id" {
  description = "Cloud Router ID"
  value       = google_compute_router.main.id
}
`,
      description: 'Output values',
      language: 'hcl',
    },
  ],
  azure: [
    {
      filename: 'main.tf',
      content: `# --------------------------------------------------
# Azure Infrastructure - Generated by Terraform Generator
# --------------------------------------------------

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "main" {
  name     = "\${var.project_name}-rg"
  location = var.location
}

resource "azurerm_virtual_network" "main" {
  name                = "\${var.project_name}-vnet"
  address_space       = [var.vnet_cidr]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_subnet" "private" {
  name                 = "private"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = [var.private_subnet_cidr]
}

resource "azurerm_subnet" "public" {
  name                 = "public"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = [var.public_subnet_cidr]
}
`,
      description: 'Main Azure infrastructure',
      language: 'hcl',
    },
    {
      filename: 'variables.tf',
      content: `variable "project_name" {
  description = "Project name"
  type        = string
  default     = "my-infra"
}

variable "location" {
  description = "Azure region"
  type        = string
  default     = "West Europe"
}

variable "vnet_cidr" {
  description = "VNet CIDR"
  type        = string
  default     = "10.0.0.0/16"
}

variable "private_subnet_cidr" {
  type    = string
  default = "10.0.1.0/24"
}

variable "public_subnet_cidr" {
  type    = string
  default = "10.0.2.0/24"
}
`,
      description: 'Variable definitions',
      language: 'hcl',
    },
  ],
};

export default function App() {
  // Input state
  const [description, setDescription] = useState('');
  const [provider, setProvider] = useState<CloudProvider>('aws');
  const [securityLevel, setSecurityLevel] = useState<SecurityLevel>('standard');
  const [requirements, setRequirements] = useState<string[]>([]);

  // Output state
  const [files, setFiles] = useState<GeneratedFile[]>([]);
  const [validation, setValidation] = useState<ValidationResult | null>(null);
  const [securityNotes, setSecurityNotes] = useState<string[]>([]);
  const [estimatedCost, setEstimatedCost] = useState('');
  const [generationId, setGenerationId] = useState<string | null>(null);

  // UI state
  const [isGenerating, setIsGenerating] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);

  const handleGenerate = useCallback(async () => {
    if (!description.trim() || isGenerating) return;

    setIsGenerating(true);
    try {
      const response = await api.generate({
        description,
        provider,
        security_level: securityLevel,
        requirements,
      });

      setFiles(response.files);
      setValidation(response.validation);
      setSecurityNotes(response.security_notes);
      setEstimatedCost(response.estimated_cost);
      setGenerationId(response.id);
    } catch {
      // Fallback to mock data for demo purposes
      const mockFiles = MOCK_FILES[provider];
      setFiles(mockFiles);
      setValidation({
        valid: true,
        errors: [],
        warnings:
          securityLevel === 'standard'
            ? ['Consider enabling encryption at rest for all storage resources']
            : [],
      });
      setSecurityNotes(
        securityLevel === 'strict'
          ? [
              'All S3 buckets configured with SSE-S3 encryption',
              'VPC Flow Logs enabled for network monitoring',
              'IMDSv2 required on all EC2 instances',
              'Security groups follow least-privilege principle',
              'CloudTrail logging enabled for audit compliance',
            ]
          : [
              'VPC Flow Logs enabled for network monitoring',
              'IMDSv2 required on bastion host',
              'Warning: SSH access is open to 0.0.0.0/0 - restrict in production',
            ]
      );
      setEstimatedCost(
        provider === 'aws'
          ? '~$65-120/month (NAT Gateway + t3.micro bastion)'
          : provider === 'gcp'
            ? '~$35-80/month (Cloud NAT + network)'
            : '~$45-90/month (VNet + subnets)'
      );
      setGenerationId('mock-' + Date.now());
    } finally {
      setIsGenerating(false);
    }
  }, [description, provider, securityLevel, requirements, isGenerating]);

  const handleDownloadZip = useCallback(async () => {
    if (!generationId || isDownloading) return;

    setIsDownloading(true);
    try {
      await api.downloadZip(generationId);
    } catch {
      // Fallback: create zip client-side from current files
      const content = files
        .map((f) => `# === ${f.filename} ===\n${f.content}`)
        .join('\n\n');
      const blob = new Blob([content], { type: 'text/plain' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `terraform-${provider}.tf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    } finally {
      setIsDownloading(false);
    }
  }, [generationId, isDownloading, files, provider]);

  const handleHistorySelect = useCallback(
    async (id: string) => {
      try {
        const response = await api.getGeneration(id);
        setFiles(response.files);
        setValidation(response.validation);
        setSecurityNotes(response.security_notes);
        setEstimatedCost(response.estimated_cost);
        setGenerationId(response.id);
        setProvider(response.provider);
      } catch {
        // If the backend is not available, just close
      }
    },
    []
  );

  return (
    <div className="flex flex-col h-screen bg-vscode-bg text-vscode-text">
      {/* Header */}
      <header className="flex items-center justify-between px-5 py-3 bg-vscode-sidebar border-b border-vscode-border shrink-0">
        <div className="flex items-center gap-3">
          <div className="flex items-center justify-center w-8 h-8 rounded bg-vscode-accent/20">
            <Code2 className="w-5 h-5 text-vscode-accent" />
          </div>
          <div>
            <h1 className="text-base font-semibold tracking-tight leading-none">
              Terraform Generator
            </h1>
            <p className="text-xs text-vscode-text-muted mt-0.5">
              AI-Powered Infrastructure as Code
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="flex items-center gap-1.5 text-xs text-vscode-text-muted px-2 py-1 rounded bg-vscode-input border border-vscode-border">
            <Zap className="w-3 h-3 text-vscode-warning" />
            Powered by AI
          </span>
          <button
            onClick={() => setHistoryOpen(true)}
            className="btn-secondary py-1.5 px-3 text-sm"
          >
            <History className="w-4 h-4" />
            History
          </button>
        </div>
      </header>

      {/* Main Content - Split View */}
      <div className="flex flex-1 min-h-0 overflow-hidden">
        {/* Left Panel - Description Input */}
        <div className="w-[40%] min-w-[360px] border-r border-vscode-border bg-vscode-sidebar overflow-y-auto">
          <DescriptionInput
            description={description}
            provider={provider}
            securityLevel={securityLevel}
            requirements={requirements}
            isGenerating={isGenerating}
            onDescriptionChange={setDescription}
            onProviderChange={setProvider}
            onSecurityLevelChange={setSecurityLevel}
            onRequirementsChange={setRequirements}
            onGenerate={handleGenerate}
          />
        </div>

        {/* Right Panel - Code Viewer + Security Notes */}
        <div className="flex-1 flex flex-col min-w-0 bg-vscode-bg">
          <div className="flex-1 min-h-0">
            <CodeViewer
              files={files}
              validation={validation}
              generationId={generationId}
              onDownloadZip={handleDownloadZip}
              isDownloading={isDownloading}
            />
          </div>
          {files.length > 0 && (
            <SecurityNotes
              notes={securityNotes}
              estimatedCost={estimatedCost}
            />
          )}
        </div>
      </div>

      {/* History Panel */}
      <HistoryPanel
        isOpen={historyOpen}
        onClose={() => setHistoryOpen(false)}
        onSelect={handleHistorySelect}
      />
    </div>
  );
}
